theme = "soho"
baseurl = "/"
languageCode = "en"
title = "Gina Carrion"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
summarylength = 10
enableEmoji = true
paginate = 5

[params]
title = "Gina Carrion"
description = "ginacarrion@utexas.edu"
images = ["images/profile.png"]
profilePicture = "images/ginagrad.jpg"
copyright = "Gina Carrion"
license = "CC BY-SA 4.0"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
builtWith = true
mainSections = ["post"]

## Set custom theme color.
# themeColor = "#fc2803"

  [[params.socialIcons]]
  icon = "fa-linkedin"
  title = "Linkedin"
  url = "https://www.linkedin.com/in/gina-carrion-492254191/"

  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "https://github.com/gmcarrion"

[taxonomies]
  series = "series"
  category = "categories"
  tag = "tags"

[menu]

  [[menu.main]]
  name = "Projects and Writing Samples"
  weight = 100
  identifier = "RStudio Projects"
  url = "/posts/"

  [[menu.main]]
  name = "About"
  identifier = "about"
  weight = 10
  url = "/about/"
  
  [[menu.main]]
  name = "Education and Experience"
  identifier = "experience"
  weight = 10
  url = "/experience/"

[markup]

  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "monokai"
  tabWidth = 4
